import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import GoogleMaps from "../components/GoogleMaps";
import ExplainResponseWidget from "../components/ExplainResponseWidget";
import AppProvider from "../context/AppProvider";

// Forward properties from `_middleware.tsx`
// When support for configuring gSSP to use Edge Functions lands,
// We could add that logic here directly.
export const getServerSideProps = ({ query }) => ({
  props: query,
});

const Home: NextPage = ({ location }) => {
  return (
    <AppProvider>
      <div className={styles.container}>
        <Head>
          <title>Very Good Address</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <main className={styles.main}>
          <h1 className={styles.title}>Very Good Address!</h1>

          <div className={styles.grid}>
            <div className={styles.card}>
              <h2>Location-Verified Addresses for Customer Onboarding</h2>
              <p>
                Address verification using the location services of mobile
                devices is the fastests, lowest friction alternative to
                validating an address when traditional identity verification
                methods fail.
              </p>
              <p>
                Very Good Address makes it easy to integrate location-verified
                addresses into your onboarding process through our API service.
              </p>
            </div>
          </div>
          <div className={styles.grid}>
            <GoogleMaps location={JSON.parse(location)} />
          </div>
          <div>
            <ExplainResponseWidget />
          </div>
        </main>

        <footer className={styles.footer}>
          All rights reserved
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </footer>
      </div>
    </AppProvider>
  );
};

export default Home;
