import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import GoogleMaps from "../components/GoogleMaps";

// Forward properties from `_middleware.tsx`
// When support for configuring gSSP to use Edge Functions lands,
// We could add that logic here directly.
export const getServerSideProps = ({ query }) => ({
  props: query,
});

const Home: NextPage = ({
  name,
  languages,
  city,
  region,
  country,
  currencyCode,
  currencySymbol,
}) => {
  console.log(
    name,
    languages,
    city,
    region,
    country,
    currencyCode,
    currencySymbol
  );
  return (
    <div className={styles.container}>
      <Head>
        <title>Very Good Address</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Very Good Address!</h1>

        <div className={styles.grid}>
          <a className={styles.card}>
            <h2>Location-Verified Addresses for Customer Onboarding</h2>
            <p>
              Address verification using the location services of mobile devices
              is the fastests, lowest friction alternative to validating an
              address when traditional identity verification methods fail.
            </p>
            <p>
              Very Good Address makes it easy to integrate location-verified
              addresses into your onboarding process through our API service.
            </p>
          </a>

          <a href="https://nextjs.org/learn" className={styles.card}>
            <h2>Learn &rarr;</h2>
            <p>Learn about Next.js in an interactive course with quizzes!</p>
          </a>

          <a
            href="https://github.com/vercel/next.js/tree/master/examples"
            className={styles.card}
          >
            <h2>Examples &rarr;</h2>
            <p>Discover and deploy boilerplate example Next.js projects.</p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
          >
            <h2>Deploy &rarr;</h2>
            <p>
              Instantly deploy your Next.js site to a public URL with Vercel.
            </p>
          </a>
        </div>
        <div className={styles.grid}>
          <GoogleMaps />
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
};

export default Home;
